server:
  port: 8079
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://keycloak:8080/realms/specific-group-realm
  cloud:
    discovery:
      enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/score/**

        - id: todolist-service
          uri: lb://todolist-service
          predicates:
            - Path=/api/v1/task/**
            - Path=/api/v1/task-group/**

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/user/**

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
logging:
  level:
    org:
      springframework:
        security: DEBUG