server:
  port: 8079
spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8282/realms/specific-group-realm/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8282/realms/specific-group-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: authentication-service
          uri: lb://authentication-service/
          predicates:
            - Path=/*/*/user/**
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway