server:
  port: 9093

spring:
  jpa:
    show-sql: true
  application:
    name: rating-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/rating_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/changelog.yml

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

amqp:
  exchange:
    task: task.topic
  queue:
    task: task.queue

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG