server:
  port: 9091

spring:
  application:
    name: authentication-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka #http://eureka-service:8761/eureka

logging:
  level:
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN

keycloak:
  serverUrl: http://localhost:8484/auth
  realm: specific-group-realm
  client:
    id: admin-cli
    secret: XNy7Mtjm6bJOcv5SvdkFnSWfCtph9Rtz
  username: admin
  password: admin_password
  token:
    endpoint: http://localhost:8484/auth/realms/specific-group-realm/protocol/openid-connect/token