server:
  port: 9091

spring:
  application:
    name: authentication-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka

keycloak:
  serverUrl: http://keycloak:8080
  realm: master
  client:
    id: admin-cli
  username: admin
  password: admin
  token:
    client: specific-group-client
    endpoint: http://keycloak:8080/realms/specific-group-realm/protocol/openid-connect/token
    secret: C2fMeRClc4Muy0mk4uDpss1OGZuOPyl9

logging:
  level:
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN