server:
  port: 9091

spring:
  application:
    name: authentication-service

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka

keycloak:
  serverUrl: http://keycloak:8080
#  serverUrl: http://localhost:8282
  realm: master
  client:
    id: admin-cli
  username: admin
  password: admin
  token:
    client: specific-group-client
#    endpoint: http://localhost:8282/realms/specific-group-realm/protocol/openid-connect/token
    endpoint: http://keycloak:8080/realms/specific-group-realm/protocol/openid-connect/token
    secret: XtuJKtWe7RYsWVPGQJDmY2ck31EGEcnP

logging:
  level:
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN